name: flutter_firebase_chat_core
description: Flutter Firebase Chat Core
version: 0.1.0
homepage: https://github.com/flyerhq/flutter_firebase_chat_core

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.0
  firebase_auth: ^1.0.0
  flutter_chat_types: ^2.0.3
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
